package co.themafia.hbm;
// Generated 11/03/2013 04:36:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cancion generated by hbm2java
 */
public class Cancion  implements java.io.Serializable {


     private int idCancion;
     private String nombre;
     private String duracion;
     private Integer tamano;
     private Integer calidad;
     private Integer precio;
     private Set<Disco> discos = new HashSet<Disco>(0);
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);
     private Set<Recopilacion> recopilacions = new HashSet<Recopilacion>(0);

    public Cancion() {
    }

	
    public Cancion(int idCancion) {
        this.idCancion = idCancion;
    }
    public Cancion(int idCancion, String nombre, String duracion, Integer tamano, Integer calidad, Integer precio, Set<Disco> discos, Set<Pedido> pedidos, Set<Recopilacion> recopilacions) {
       this.idCancion = idCancion;
       this.nombre = nombre;
       this.duracion = duracion;
       this.tamano = tamano;
       this.calidad = calidad;
       this.precio = precio;
       this.discos = discos;
       this.pedidos = pedidos;
       this.recopilacions = recopilacions;
    }
   
    public int getIdCancion() {
        return this.idCancion;
    }
    
    public void setIdCancion(int idCancion) {
        this.idCancion = idCancion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public Integer getTamano() {
        return this.tamano;
    }
    
    public void setTamano(Integer tamano) {
        this.tamano = tamano;
    }
    public Integer getCalidad() {
        return this.calidad;
    }
    
    public void setCalidad(Integer calidad) {
        this.calidad = calidad;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public Set<Disco> getDiscos() {
        return this.discos;
    }
    
    public void setDiscos(Set<Disco> discos) {
        this.discos = discos;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }
    public Set<Recopilacion> getRecopilacions() {
        return this.recopilacions;
    }
    
    public void setRecopilacions(Set<Recopilacion> recopilacions) {
        this.recopilacions = recopilacions;
    }




}


