package co.themafia.hbm;
// Generated 10/03/2013 10:50:03 PM by Hibernate Tools 3.2.1.GA



/**
 * ConceptousuarioId generated by hbm2java
 */
public class ConceptousuarioId  implements java.io.Serializable {


     private int idConcepto;
     private int idPedido;

    public ConceptousuarioId() {
    }

    public ConceptousuarioId(int idConcepto, int idPedido) {
       this.idConcepto = idConcepto;
       this.idPedido = idPedido;
    }
   
    public int getIdConcepto() {
        return this.idConcepto;
    }
    
    public void setIdConcepto(int idConcepto) {
        this.idConcepto = idConcepto;
    }
    public int getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConceptousuarioId) ) return false;
		 ConceptousuarioId castOther = ( ConceptousuarioId ) other; 
         
		 return (this.getIdConcepto()==castOther.getIdConcepto())
 && (this.getIdPedido()==castOther.getIdPedido());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdConcepto();
         result = 37 * result + this.getIdPedido();
         return result;
   }   


}


