package co.themafia.hbm;
// Generated 10/03/2013 10:50:03 PM by Hibernate Tools 3.2.1.GA



/**
 * Conceptousuario generated by hbm2java
 */
public class Conceptousuario  implements java.io.Serializable {


     private ConceptousuarioId id;
     private Pedido pedido;
     private String concepto;

    public Conceptousuario() {
    }

	
    public Conceptousuario(ConceptousuarioId id, Pedido pedido) {
        this.id = id;
        this.pedido = pedido;
    }
    public Conceptousuario(ConceptousuarioId id, Pedido pedido, String concepto) {
       this.id = id;
       this.pedido = pedido;
       this.concepto = concepto;
    }
   
    public ConceptousuarioId getId() {
        return this.id;
    }
    
    public void setId(ConceptousuarioId id) {
        this.id = id;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }




}


