package co.themafia.hbm;
// Generated 11/03/2013 04:36:19 PM by Hibernate Tools 3.2.1.GA



/**
 * Conceptousuario generated by hbm2java
 */
public class Conceptousuario  implements java.io.Serializable {


     private ConceptousuarioId id;
     private Pedido pedido;
     private String concepto;
     private Integer calificacion;
     private String fechaConcepto;

    public Conceptousuario() {
    }

	
    public Conceptousuario(ConceptousuarioId id, Pedido pedido) {
        this.id = id;
        this.pedido = pedido;
    }
    public Conceptousuario(ConceptousuarioId id, Pedido pedido, String concepto, Integer calificacion, String fechaConcepto) {
       this.id = id;
       this.pedido = pedido;
       this.concepto = concepto;
       this.calificacion = calificacion;
       this.fechaConcepto = fechaConcepto;
    }
   
    public ConceptousuarioId getId() {
        return this.id;
    }
    
    public void setId(ConceptousuarioId id) {
        this.id = id;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }
    public String getFechaConcepto() {
        return this.fechaConcepto;
    }
    
    public void setFechaConcepto(String fechaConcepto) {
        this.fechaConcepto = fechaConcepto;
    }




}


