package co.themafia.hbm;
// Generated 10/03/2013 10:50:03 PM by Hibernate Tools 3.2.1.GA



/**
 * Confirmacion generated by hbm2java
 */
public class Confirmacion  implements java.io.Serializable {


     private ConfirmacionId id;
     private Pedido pedido;
     private Boolean aceptada;
     private Boolean despachada;
     private String observacion;

    public Confirmacion() {
    }

	
    public Confirmacion(ConfirmacionId id, Pedido pedido) {
        this.id = id;
        this.pedido = pedido;
    }
    public Confirmacion(ConfirmacionId id, Pedido pedido, Boolean aceptada, Boolean despachada, String observacion) {
       this.id = id;
       this.pedido = pedido;
       this.aceptada = aceptada;
       this.despachada = despachada;
       this.observacion = observacion;
    }
   
    public ConfirmacionId getId() {
        return this.id;
    }
    
    public void setId(ConfirmacionId id) {
        this.id = id;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Boolean getAceptada() {
        return this.aceptada;
    }
    
    public void setAceptada(Boolean aceptada) {
        this.aceptada = aceptada;
    }
    public Boolean getDespachada() {
        return this.despachada;
    }
    
    public void setDespachada(Boolean despachada) {
        this.despachada = despachada;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


