package co.themafia.hbm;
// Generated 11/03/2013 04:36:19 PM by Hibernate Tools 3.2.1.GA



/**
 * Confirmacion generated by hbm2java
 */
public class Confirmacion  implements java.io.Serializable {


     private ConfirmacionId id;
     private Pedido pedido;
     private Boolean aceptada;
     private Boolean despachada;
     private String observacion;
     private String fechaEnvio;

    public Confirmacion() {
    }

	
    public Confirmacion(ConfirmacionId id, Pedido pedido) {
        this.id = id;
        this.pedido = pedido;
    }
    public Confirmacion(ConfirmacionId id, Pedido pedido, Boolean aceptada, Boolean despachada, String observacion, String fechaEnvio) {
       this.id = id;
       this.pedido = pedido;
       this.aceptada = aceptada;
       this.despachada = despachada;
       this.observacion = observacion;
       this.fechaEnvio = fechaEnvio;
    }
   
    public ConfirmacionId getId() {
        return this.id;
    }
    
    public void setId(ConfirmacionId id) {
        this.id = id;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Boolean getAceptada() {
        return this.aceptada;
    }
    
    public void setAceptada(Boolean aceptada) {
        this.aceptada = aceptada;
    }
    public Boolean getDespachada() {
        return this.despachada;
    }
    
    public void setDespachada(Boolean despachada) {
        this.despachada = despachada;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getFechaEnvio() {
        return this.fechaEnvio;
    }
    
    public void setFechaEnvio(String fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }




}


