package co.themafia.hbm;
// Generated 10/03/2013 10:50:03 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Disco generated by hbm2java
 */
public class Disco  implements java.io.Serializable {


     private int idDisco;
     private Proveedor proveedor;
     private String nombre;
     private String artista;
     private String imagen;
     private String genero;
     private Integer ano;
     private Boolean digital;
     private Boolean vinilo;
     private Integer precioDigital;
     private Integer precioVinilo;
     private String cantidadVinilo;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);
     private Set<Cancion> cancions = new HashSet<Cancion>(0);

    public Disco() {
    }

	
    public Disco(int idDisco, Proveedor proveedor) {
        this.idDisco = idDisco;
        this.proveedor = proveedor;
    }
    public Disco(int idDisco, Proveedor proveedor, String nombre, String artista, String imagen, String genero, Integer ano, Boolean digital, Boolean vinilo, Integer precioDigital, Integer precioVinilo, String cantidadVinilo, Set<Pedido> pedidos, Set<Cancion> cancions) {
       this.idDisco = idDisco;
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.artista = artista;
       this.imagen = imagen;
       this.genero = genero;
       this.ano = ano;
       this.digital = digital;
       this.vinilo = vinilo;
       this.precioDigital = precioDigital;
       this.precioVinilo = precioVinilo;
       this.cantidadVinilo = cantidadVinilo;
       this.pedidos = pedidos;
       this.cancions = cancions;
    }
   
    public int getIdDisco() {
        return this.idDisco;
    }
    
    public void setIdDisco(int idDisco) {
        this.idDisco = idDisco;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getArtista() {
        return this.artista;
    }
    
    public void setArtista(String artista) {
        this.artista = artista;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Integer getAno() {
        return this.ano;
    }
    
    public void setAno(Integer ano) {
        this.ano = ano;
    }
    public Boolean getDigital() {
        return this.digital;
    }
    
    public void setDigital(Boolean digital) {
        this.digital = digital;
    }
    public Boolean getVinilo() {
        return this.vinilo;
    }
    
    public void setVinilo(Boolean vinilo) {
        this.vinilo = vinilo;
    }
    public Integer getPrecioDigital() {
        return this.precioDigital;
    }
    
    public void setPrecioDigital(Integer precioDigital) {
        this.precioDigital = precioDigital;
    }
    public Integer getPrecioVinilo() {
        return this.precioVinilo;
    }
    
    public void setPrecioVinilo(Integer precioVinilo) {
        this.precioVinilo = precioVinilo;
    }
    public String getCantidadVinilo() {
        return this.cantidadVinilo;
    }
    
    public void setCantidadVinilo(String cantidadVinilo) {
        this.cantidadVinilo = cantidadVinilo;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }
    public Set<Cancion> getCancions() {
        return this.cancions;
    }
    
    public void setCancions(Set<Cancion> cancions) {
        this.cancions = cancions;
    }




}


