package co.themafia.hbm;
// Generated 11/03/2013 04:36:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estadopedido generated by hbm2java
 */
public class Estadopedido  implements java.io.Serializable {


     private int idEstado;
     private String estado;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Estadopedido() {
    }

	
    public Estadopedido(int idEstado) {
        this.idEstado = idEstado;
    }
    public Estadopedido(int idEstado, String estado, Set<Pedido> pedidos) {
       this.idEstado = idEstado;
       this.estado = estado;
       this.pedidos = pedidos;
    }
   
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


