package co.themafia.hbm;
// Generated 10/03/2013 10:50:03 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Mediopago generated by hbm2java
 */
public class Mediopago  implements java.io.Serializable {


     private int idMedioPago;
     private String medioPago;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Mediopago() {
    }

	
    public Mediopago(int idMedioPago) {
        this.idMedioPago = idMedioPago;
    }
    public Mediopago(int idMedioPago, String medioPago, Set<Pedido> pedidos) {
       this.idMedioPago = idMedioPago;
       this.medioPago = medioPago;
       this.pedidos = pedidos;
    }
   
    public int getIdMedioPago() {
        return this.idMedioPago;
    }
    
    public void setIdMedioPago(int idMedioPago) {
        this.idMedioPago = idMedioPago;
    }
    public String getMedioPago() {
        return this.medioPago;
    }
    
    public void setMedioPago(String medioPago) {
        this.medioPago = medioPago;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


