package co.themafia.hbm;
// Generated 11/03/2013 04:36:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private int idProveedor;
     private String nombre;
     private String apellido;
     private String email;
     private String contrasena;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);
     private Set<Disco> discos = new HashSet<Disco>(0);

    public Proveedor() {
    }

	
    public Proveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Proveedor(int idProveedor, String nombre, String apellido, String email, String contrasena, Set<Pedido> pedidos, Set<Disco> discos) {
       this.idProveedor = idProveedor;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.contrasena = contrasena;
       this.pedidos = pedidos;
       this.discos = discos;
    }
   
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }
    public Set<Disco> getDiscos() {
        return this.discos;
    }
    
    public void setDiscos(Set<Disco> discos) {
        this.discos = discos;
    }




}


