package co.themafia.hbm;
// Generated 10/03/2013 10:50:03 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String nombre;
     private String apellido;
     private String email;
     private Integer cantidadCompras;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);
     private Set<Recopilacion> recopilacions = new HashSet<Recopilacion>(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario(int idUsuario, String nombre, String apellido, String email, Integer cantidadCompras, Set<Pedido> pedidos, Set<Recopilacion> recopilacions) {
       this.idUsuario = idUsuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.cantidadCompras = cantidadCompras;
       this.pedidos = pedidos;
       this.recopilacions = recopilacions;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getCantidadCompras() {
        return this.cantidadCompras;
    }
    
    public void setCantidadCompras(Integer cantidadCompras) {
        this.cantidadCompras = cantidadCompras;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }
    public Set<Recopilacion> getRecopilacions() {
        return this.recopilacions;
    }
    
    public void setRecopilacions(Set<Recopilacion> recopilacions) {
        this.recopilacions = recopilacions;
    }




}


